//https://microsoft.github.io/monaco-editor/typedoc/interfaces/editor.IEditorConstructionOptions.html#stickyScroll

// editorOptions.js
export default {
  fontSize: 26,
  semicolon: true,
  fontFamily: 'Monaco, MonoLisa, monospace',
  formatOnType: true,
  formatOnPaste: true,
  formatOnSave: true,
  automaticLayout: true,
  showFoldingControls: 'mouseover',
  showUnused: true,
  smoothScrolling: true,
  wordWrap: 'off',
  stickyScroll: true,
  minimap: { enabled: true, side: 'right' },
  lineNumbers: 'on',
  renderControlCharacters: true,
  cursorStyle: 'line',
  cursorBlinking: 'blink',
  autoClosingBrackets: true,
  autoClosingQuotes: true,
  autoIndent: 'full',
  tabSize: 2,
  insertSpaces: true,
  highlightActiveIndentGuide: true,
  find: {
    autoFindInSelection: 'never',
  },
  quickSuggestions: {
    other: true,
    comments: true,
    strings: true,
  },
  suggestOnTriggerCharacters: true,
  parameterHints: true,
  autoSave: 'onWindowChange',
  scrollbar: {
    vertical: 'auto',
    horizontal: 'auto',
  },
  overviewRulerLanes: 3,
  fontLigatures: true,
  selectionHighlight: true,
  renderLineHighlight: 'all',
  folding: true,
  lineDecorationsWidth: 10,
  rulers: [120],
  glyphMargin: false,
  scrollBeyondLastColumn: 5,
  // Add these for better autocompletion
  suggest: {
    snippets: 'inline',
    showIcons: true,
    showStatusBar: true,
    preview: true,
    filterGraceful: true,
    localityBonus: true,
  },
};